### ISSUE TITLE
Draft text: Using ethn.io to recruit users through twitter, blogs, or email listervs.

### ISSUE THREAD

**Issue by jehlers** [18F/design#10]
@NoahKunin we've created an initial draft of guidance for the team when using a direct ethnio link outside of the normal usage on a website. Please look it over and let us know what you think!

https://docs.google.com/document/d/1zsFCHrh5MB-yU71g-BjRM9oHo_Xnnjw5KMhBOkOIEds/edit#

**Comment by jehlers** [comment]
@NoahKunin any thoughts?

**Comment by NoahKunin** [comment]
@jehlers LGTM

**Comment by NoahKunin** [comment]
Just ping me via Slack once the PR into the Hanbook is merged.

**Comment by jehlers** [comment]
Thanks @NoahKunin!
